name: Generate Sitemap
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate XML sitemap
        uses: jakejarvis/sitemap-action@master
        with:
          domain: https://ayodhyatourism.services 
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git diff --staged --quiet || (git commit -m "Automated sitemap update [skip ci]" && git push)